### ISSUE TITLE
top画面作成

### ISSUE THREAD

**Issue by takumiTakahata** [morijyobi/python_flask_web_final_exercise_2023-takumiTakahata#3]
## 目的
ログインボタンをを押すとログイン画面へ遷移
管理者ログインボタンを押すと管理者ログイン画面へ遷移

## 作成
- [x] ログインボタンの作成
- [x] 管理者ログインボタンの作成

## レイアウト例
<img width="820" alt="image" src="https://github.com/morijyobi/python_flask_web_final_exercise_2023-takumiTakahata/assets/113155629/c6a43db5-428b-44ba-bea5-d521114a21ad">

**Comment by hosokawa3217** [comment]
いいね！

**Comment by takumiTakahata** [comment]
装飾は後でやります

**Comment by hosokawa3217** [comment]
これで十分ですよー
